(()=>{'use strict';const status=document.querySelector('#status'),enter=document.querySelector('#enter'),retry=document.querySelector('#retry'),frame=document.querySelector('#shop');let busy=false,active='',memory='';
function key(){try{memory=localStorage.getItem('lige-shop-device-v1')||memory;}catch{}if(!/^[a-f0-9]{64}$/.test(memory)){memory=Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');try{localStorage.setItem('lige-shop-device-v1',memory);}catch{}}return memory;}
function visitor(){let v='';try{v=localStorage.getItem('lige-shop-visitor-v1')||'';}catch{}if(!/^[a-f0-9]{64}$/.test(v)){v=Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');try{localStorage.setItem('lige-shop-visitor-v1',v);}catch{}}return v;}
frame.addEventListener('load',()=>{if(active)frame.contentWindow.postMessage({type:'shop-device',key:key(),visitor:visitor(),source:new URLSearchParams(location.search).get('utm_source')||'direct'},new URL(active).origin);});
window.addEventListener('message',e=>{if(e.source===frame.contentWindow&&active&&e.origin===new URL(active).origin&&e.data?.type==='shop-forget-device'){memory='';try{localStorage.removeItem('lige-shop-device-v1');}catch{}frame.contentWindow.postMessage({type:'shop-device',key:key(),visitor:visitor(),source:new URLSearchParams(location.search).get('utm_source')||'direct'},new URL(active).origin);}});
async function timedFetch(url){const c=new AbortController(),timer=setTimeout(()=>c.abort(),12000);try{return await fetch(url,{cache:'no-store',signal:c.signal});}finally{clearTimeout(timer);}}
async function connect(){if(busy)return;busy=true;retry.hidden=true;try{
let config=null;const stamp=Date.now(),sources=['https://raw.githubusercontent.com/lz850522055-bot/lige-shop-entry/main/target.json?t='+stamp,'target.json?t='+stamp];for(const source of sources){try{const r=await timedFetch(source);if(!r.ok)continue;const candidate=await r.json(),u=new URL(candidate.url);if(u.protocol!=='https:'||!['.trycloudflare.com','.tunnelmole.net'].some(s=>u.hostname.endsWith(s)))continue;const h=await timedFetch(u.origin+'/health');if(h.ok&&(await h.json()).ok){config=candidate;break;}}catch{}}if(!config)throw Error();
if(!config.url)throw Error();const url=new URL(config.url);if(url.protocol!=='https:'||!['.trycloudflare.com','.tunnelmole.net'].some(suffix=>url.hostname.endsWith(suffix)))throw Error();
enter.href=url.href;
status.textContent='店铺已连接';if(active!==url.href){active=url.href;frame.src=active;}frame.hidden=false;document.querySelector('.card').hidden=true;
}catch{status.textContent='正在自动恢复连接，请稍候，无需更换二维码。';enter.hidden=true;retry.hidden=false;if(!active){frame.hidden=true;document.querySelector('.card').hidden=false;}}finally{busy=false;}}
retry.addEventListener('click',connect);connect();setInterval(connect,15000);})();
